import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./page"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <main className="flex w-full h-full">
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
