# Generated by Django 5.0.1 on 2024-02-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to='static/users/posts/'),
        ),
    ]
