# Generated by Django 5.0.1 on 2024-03-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_hashtags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Hashtag', 'verbose_name_plural': 'Hashtags'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postfile',
            options={'verbose_name': 'PostFile', 'verbose_name_plural': 'PostFiles'},
        ),
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name': 'PostLike', 'verbose_name_plural': 'PostLikes'},
        ),
    ]
