# Generated by Django 5.0.1 on 2024-03-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('user', '0008_delete_lockedusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_posts', through='post.PostViewsHistory', to='user.user'),
        ),
    ]
