# Generated by Django 5.0.1 on 2024-04-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_story_caption_alter_story_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.FileField(upload_to="[WindowsPath('E:/Programming/gitProjects/instagram-mock/backend/static')]users/stories/"),
        ),
    ]
