# Generated by Django 5.0.1 on 2024-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_follows_follow_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('locked_until', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=100),
        ),
    ]
