# Generated by Django 5.0.1 on 2024-04-19 16:57

import utils.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=utils.model_utils.generate_path),
        ),
    ]
