# Generated by Django 5.0.1 on 2024-02-05 15:13

import django.db.models.deletion
import story.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('IMG', 'IMAGE'), ('VID', 'VIDEO')], max_length=3)),
                ('content', models.TextField()),
                ('privacy_type', models.CharField(choices=[('NRL', 'NORMAL'), ('CLS', 'CLOSE_FRIEND')], max_length=3)),
                ('active_until', models.DateTimeField(default=story.models._get_story_lifetime)),
                ('likes', models.ManyToManyField(related_name='user_story_likes', to='user.user')),
                ('tags', models.ManyToManyField(related_name='user_story_tags', to='user.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='StoryViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.ManyToManyField(related_name='user_story_views', through='story.StoryViews', to='user.user'),
        ),
    ]
