# Generated by Django 5.0.1 on 2024-03-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.FileField(upload_to='static/users/stories/'),
        ),
    ]
