# Generated by Django 5.0.1 on 2024-02-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followrequest_user_follow_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_folowings', to='user.user'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='user.user'),
        ),
    ]
