# Generated by Django 5.0.1 on 2024-02-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', to='user.user'),
        ),
    ]
