# Generated by Django 5.0.1 on 2024-03-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_lockedusername_alter_user_salt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LockedUsername',
        ),
    ]
