# Generated by Django 5.0.1 on 2024-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('user', '0003_alter_user_close_friends_alter_user_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_comment_likes', through='comment.CommentLikes', to='user.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='user_comment_tags', to='user.user'),
        ),
    ]
