import "@/app/globals.css";
import { Inter } from "next/font/google";
import { NavBar } from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
          <div className="h-full">
            <NavBar />
          </div>
          <div className="flex flex-row w-full justify-center mt-10">{children}</div>
      </body>
    </html>
  );
}
